
# Metoda H&uuml;ckel'a
*Roberto Di Remigio*, *Luca Frediani*
tłumaczenie polskie i korekta: *Filip Brzęk*

Metoda zaproponowana przez [H&uuml;ckel]'a, jest metodą, która w sposób przybliżony pozwala na wyznaczenie poziomów energetycznych układów, w układach z sprzężęniem wielokrotnym wiązania [wiki]. Kluczową rolę odgrywają tu tzw. elektrony $\pi$, czyli elektrony zajmujące orbitale $\pi$ (prostopadłe do płaszczyzny molekuły).

Z tego powodu metoda ta ograniczona jest do układów planarnych (płaskich - 2D), układów sprzężonych wiązań wielokrotnych, zazwyczaj rozważane są łańcuchy węglowodorów.
Opis kwantowo-mechaniczny uwzględnia jedynie elektrony $\pi$. Pozstałe elektrony rdzenia (ang. *core*) (np. elektrony $\sigma$) są pomijane, jako że ich energia jest dużo niższa i zakłada się, że nie wpływają w istotny sposób na własności molekularne układu.

Orbitale molekularne (ang. *MOs*) buduje się jako kombinację liniową orbitali atomowych (LCAO - ang. linear combinantion of atomic orbilas). Przy czym bazą atomową (ang. *AO*) są jedynie orbitale $p_z$ zlokalizowane na każdym z atomów węgla.

[wiki]: https://pl.wikipedia.org/wiki/Sprz%C4%99%C5%BCone_wi%C4%85zania_wielokrotne
[H&uuml;ckel]: https://en.wikipedia.org/wiki/H%C3%BCckel_method


## Zasada Wariacyjna i równania sekularne

Jeśli $N$ jest liczbą atomów węgla w rozważanej molekule, to próbną funkcję falową możemy zapisać jako: 

\begin{equation}
\Psi = \sum_{i=1}^{N}c_i\chi_i
\end{equation}

gdzie, indeks sumacyjny $i$ przebiega po wszystkich rozważanych atomach węgla, a $\chi_i$ jest orbitalem $p_z$ umiejscowionym na $i$-tym atomie węgla w rozważanej molekule.

Funkcjonał energii całkowitej układu można zapisać jako wartość oczekiwaną operatora Hamiltona układu w przestrzeni funkcji próbnych, jako:

\begin{equation}
E(\mathbf{c}^\dagger, \mathbf{c}) = \frac{\langle \Psi | H | \Psi \rangle}{\langle \Psi | \Psi \rangle}
= \frac{\sum_{i,j=1}^{N} c_i^*H_{ij}c_j }{\sum_{i, j=1}^{N}c_i^*S_{ij}c_j}
= \frac{\mathbf{c}^\dagger\mathbf{H}\mathbf{c}}{\mathbf{c}^\dagger\mathbf{S}\mathbf{c}}
\end{equation}

gdzie, wprowadzono następujące elementy macierzowe operatora Hamiltona oraz tzw. całki nakrywania, jako:

\begin{alignat}{2}
H_{ij} = \langle \chi_i | H |\chi_j\rangle \quad& S_{ij} = \langle \chi_i | \chi_j \rangle
\end{alignat}

Zasada wariancyjna gwarantuje nam, że minimalizacja wartości funkcjonału energii jest zrealizowana dla "najlepszej" funkcji próbnej $\Psi$, w naszym przypadku w rodzinie funkcji LCAO danej bazy atomowej (funkcji $p_z$).
Policzenie odpowiednich pochodnych cząstkowych po współczynnikach $c_i$ i znalezienie ich miejsc zerowych prowadzi do, uogólnionego problemu własnego, który można zapisać w postaci:

\begin{equation}
\mathbf{H}\mathbf{c} = \mathbf{S}\mathbf{c}E
\end{equation}

gdzie **wektory własne** $\mathbf{c}$ są zbiorem współczynników przy odpowiednich funkcjach AO, opisujących dany orbital **MO**, a **wartość własna** jest energią tego orbitalu - $E$. 
Formalnie, zagadanienie własne rozwiązuje się poprzez wyznaczenie wyznacznika macierzy: $\mathbf{H} - E\mathbf{S}$, i rozwiązanie następującego równania:

\begin{equation}
\det(\mathbf{H} - E\mathbf{S}) = 0
\end{equation}

Tak zapisana metoda wariacyjna znana też jest pod postącią [metody Ritza], użyjemy jej w dalszej części w celu wyznaczenia współczynników rozkładu w methodzie H&uuml;ckel'a.

[metody Ritza]: https://pl.wikipedia.org/wiki/Metoda_Ritza

## Zagadnienie własne w metodzie H&uuml;ckel'a

Jak już wspomniano, orbitale molekularne (MO) są zbudowane jako liniowa kombinacja orbitali atomowych (LCAO), gdzie orbitale atomowe (AO) są orbitalami $p_z$ na każdym z atomów węgla. Schematyczny widok modelu przedstawiono na poniższym rysunku.

<figure>
  <IMG SRC="huckel.png">
</figure>

Elementy macierzowe Hamiltonianu i macierzy nakrywania orbitali wyznacza (czasami mówi się na te elementy - całki) się przy pomocy następujących reguł (założeń metody H&uuml;ckel'a):

* całki nakrywania pomiędzy dwoma różnymi orbitalami kładziemy jako równe zero, a nakrywanie orbitala z samym sobą jest równe jedności:

\begin{equation}
S_{ii} = 1 \quad S_{ij} = 0 \,\,\,\text{dla}\,\, i\neq j
\end{equation}

* wszystkie diagonalne elementy macierzowe Hamiltonianu są sobie równe (żaden orbital $p_z$ nie jest wyróżniony!):

\begin{equation}
H_{ii} = \alpha \,\,\,\forall i
\end{equation}

gdzie stała $\alpha$ jest parametrem modelu, pochodzącą z własności atomowych (ang. *atomic Coulomb integral*). Za jej wartość przyjmuje się zazwyczaj energię izolowanego orbitalu $2p_z$. W takim przypadku $\alpha$ jest **liczbą ujemną**! 

* wszystkie niediagonalne elementy Hamiltonianu są sobie równe (żadne oddziaływanie pomiędzy orbitaliami $p_z$ nie jest wyróżnione!). Wartości te nie są zerowe dla sąsiadujących atomów węgla i wynoszą dokładnie zero dla pozostałych:

\begin{equation}
H_{i, i+1} = \beta \quad H_{i, i+n} = 0 \,\,\,\text{dla}\,\,n\geq 2
\end{equation}

gdzie $\beta$ jest drugim parametrem modelu, określającym wiązanie pomiędzy sąsiadującymi orbitalami $\pi$ (ang. *bond parameter*). Również ujemnym, jego wartość można wyznaczyć eksperymentalnie, w dalszej części kursu przyjmiemy jego stałą wartość równą $\beta = -75 \,\mathrm{kJ}\cdot\mathrm{mol}^{-1}$.

W celu wyznaczenia rozwiązań równania sekularnego w modelu Huckel'a potrzebujemy: graf określający sąsiedztwo poszczegolnych atomów węgla (ang. *connectivity graph*) oraz wartości parametrów $\alpha$ i $\beta$.
Mając te trzy informację jesteśmy w stanie skonstruować macierz H&uuml;ckel'a i przystąpić do jej diagonalizacji.

### Prosty przykład liniowego węglowodoru: Eten

Molekuła Etenu składa się z dwóch atomów węgla oraz czterech atomów wodoru. Wodór zawiera jedynie elektrony na orbitalach $1s$, które w przybliżeniu Huckel'a są pomijane, wobec czego macierz H&uuml;ckela ma wymiary $2x2$ i można ją zapisać jako:

\begin{equation}
\begin{pmatrix}
\alpha & \beta \\
\beta  & \alpha
\end{pmatrix}
\end{equation}

równanie sekularne dane jest jako:

\begin{equation}
\det \begin{pmatrix}
(\alpha - E) & \beta \\
\beta  & (\alpha - E)
\end{pmatrix}
= (\alpha - E)^2 - \beta^2 = 0
\end{equation}

The solution of the second order equation gives the energies for the highest occupied molecular orbital $E_-$ (HOMO) and the lowest unoccupied molecular orbital $E_+$ (LUMO):

\begin{equation}
E_- = \alpha -\beta \quad E_+ = \alpha + \beta
\end{equation}

przerwa energetyczna dana jest jako:

\begin{equation}
E_{\rm HOMO - LUMO} = E_+ - E_- = - 2 \beta
\end{equation}

Wstawienie tych energii do równania wartości własnej do powstania dwóch różnych układów równań, których rozwiązanie wyznaczy współczynnik w kombinacjach liniowych MOs.
Należy zauważyć, że współczynniki są określone z dokładnością do współczynnika normalizacji.

## Bardziej złożony problem: Butadien

Molekuła butadienu zawiera 4 atomy węgla, wzór strukturalny prezentuje się nastepująco:

<figure>
  <IMG SRC="butadien.png">
</figure>

Nasza macierz Hamiltonianu będzie zatem miała wymiary 4x4:

\begin{equation}
\begin{pmatrix}
\alpha & \beta  & 0  & 0\\
\beta  & \alpha & \beta  & 0\\
0      & \beta  & \alpha & \beta \\
0      &  0     & \beta  & \alpha \\
\end{pmatrix}
\end{equation}

Rozwiązanie równania sekularnego wiązałoby się z rozwiązaniem wielomianu 4tego rzędu, co jest możliwe, ale jest też uciążliwe.

W celu zmniejszenia żmudności tego problemu, użyjemy świeżo przyswojonej wiedzy o `numpy` i Pythona, który pozwoli nam zautomatyzować ten proces.

Lecz zanim do tego przejdziemy, wygodnie jest "pozbyć" się stałych $\alpha$ oraz $\beta$, tak aby rozwiązywać problem w sposób "ogólny", (a nie dla konkretnych ich wartości).
Można to zrobić w dwóch krokach:

Wybierzemy skalę energii, tak aby była liczona w jednostkach $\beta$. Następnie, możemy wybrać tak nowy początek osi energii (zero), aby był równy $\alpha$. Tj. umawiamy się, że nasza nowa jednostka energii (liczona w jednostkach $\beta$, np. jedna $\beta$, dwie $\beta$y etc.), będzie miała zero dla energii równej $\alpha$. To z kolei upraszcza naszą macierz elementów operatora Hamiltona, do postaci:

\begin{equation}
\begin{pmatrix}
0 & 1 & 0 & 0 \\
1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1 \\
0 & 0 & 1 & 0 \\
\end{pmatrix}
\end{equation}


Taka macierz jest już bardzo prosta, do "potraktowania" jej wbudowanymi funkcjami `numpy`!

PS. Formalnie nasza transformacja energii ma postać: $E^{'} = \frac{E - \alpha}{\beta}$

Aby otrzymać energię w normalnych jednostkach, należy wynik przemnożyć przez $\beta$ i przesunąć o wartość $\alpha$
$E = \beta E^{'} + \alpha$.


In [20]:
def huckel_budadien():
    """ Huckel method for budadien 
    """
    import numpy as np
    from numpy import linalg as LA
    
    # create huckel matrix for budadien
    H = np.array(
        [[0.0, 1.0, 0.0, 0.0],
         [1.0, 0.0, 1.0, 0.0],
         [0.0, 1.0, 0.0, 1.0],
         [0.0, 0.0, 1.0, 0.0]
        ]
    )
    # Print H
    print('Huckel matrix is \n{}'.format(H))
    
    # Diagonalize H
    energies, orbitals = LA.eigh(H)
    # Sort eigenvalues and eigenvectors in ascending order
    sort_perm = energies.argsort()
    energies.sort()     # <-- This sorts the list in place.
    orbitals = orbitals[:, sort_perm]
    
    # Return energies and orbitals
    return energies, orbitals

energies, orbitals = huckel_budadien()
print("Computed energies are \n{}".format(energies))
print("Computed orbitals are \n{}".format(orbitals))

print("Reference values are: \n"
      "E1: alpha + 1.618... beta \n"
      "E2: alpha + 0.618... beta \n"
      "E3: alpha - 0.618... beta \n"
      "E4: alpha - 1.618... beta \n"
)

Huckel matrix is 
[[0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]]
Computed energies are 
[-1.61803399 -0.61803399  0.61803399  1.61803399]
Computed orbitals are 
[[ 0.37174803 -0.60150096 -0.60150096  0.37174803]
 [-0.60150096  0.37174803 -0.37174803  0.60150096]
 [ 0.60150096  0.37174803  0.37174803  0.60150096]
 [-0.37174803 -0.60150096  0.60150096  0.37174803]]
Reference values are: 
E1: alpha + 1.618... beta 
E2: alpha + 0.618... beta 
E3: alpha - 0.618... beta 
E4: alpha - 1.618... beta 



## Zadanie: metoda H&uuml;ckela dla n liniowych węglowodorów

Napisz funkcję Pythona, która wyznaczy energie własne i wektory własne macierzy H&uuml;ckel dla ogólnego liniowego węglowodoru.
Funkcja powinna przyjmować parametr:
* n - liczba atomów węgla,
* wartość $\alpha$ (opcjonalnie), w wariancie prostszym należy przyjąć transformację taką jak w przykładzie z butadienem,
* wartość $\beta$ (opcjonalnie), w wariancie prostszym należy przyjąć transformację taką jak w przykładzie z butadienem.

Funkcja powinna, używać `numpy` do manipulacji na macierzach i wektorach, sprawdź [funkcja `np.diag`] oraz [funkcja `np.ones`].
Moduł `numpy.linalg` zawiera niezbędne funkcje do wykonywania podstawowych operacji algebry liniowej. W naszym przypadku używać będziemy `numpy.linalg.eigh` solvera, pozwającego na wyznaczanie wartości i wektorów własnych danej macierzy, sprawdź [funkcja `eigh`]

```Python
def huckel_1D(n, alpha=0.0, beta=1.0):
    """ Huckel method
    
    n -- number of carbon atoms
    alpha -- Coulomb integral
    beta --  resonance integral
    """
    import numpy as np
    from numpy import linalg as LA
    
    H = np.zeros((n, n))
    # Fill the matrix!
    ## Fill diagonal
    
    ## Fill off-diagonal
    
    # Print H
    print('Huckel matrix is {}'.format(H))
    
    # Diagonalize H
    energies, orbitals = LA.eig(H)
    # Sort eigenvalues and eigenvectors in ascending order
    sort_perm = energies.argsort()
    energies.sort()     # <-- This sorts the list in place.
    orbitals = orbitals[:, sort_perm]
    
    # Return energies and orbitals
    return energies, orbitals
```

[funkcja `eigh`]: https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigh.html
[funkcja `np.diag`]: https://numpy.org/doc/stable/reference/generated/numpy.diag.html
[funkcja `np.ones`]: https://numpy.org/doc/stable/reference/generated/numpy.ones.html


In [ ]:
def huckel_1D(n, alpha=0.0, beta=1.0):
    """ Huckel method
    
    n -- number of carbon atoms
    alpha -- Coulomb integral
    beta --  resonance integral
    connectivity -- an array of integers defining the connectivity
    """
    import numpy as np
    from numpy import linalg as LA
    
    H = np.zeros((n, n))
    # Fill the matrix!
    ## Fill diagonal
    
    ## Fill off-diagonal
    
    # Print H
    print('Huckel matrix is \n{}'.format(H))
    
    # Diagonalize H
    energies, evecs = LA.eig(H)
    # Sort eigenvalues and eigenvectors in ascending order:q
    sort_perm = energies.argsort()
    energies.sort()     # <-- This sorts the list in place.
    orbitals = evecs[:, sort_perm]
    
    # Return energies and orbitals
    return energies, orbitals

# powinno wyjść to samo co w poprzednim przypadku, wpisanym z ręki!
energies, orbitals = huckel_1D(4)
print('Huckel model energies \n{}'.format(energies))
print('Huckel model orbitals \n{}'.format(orbitals))

<figure>
  <IMG SRC="huckel_g6.gif">
</figure>
